### ISSUE TITLE
CMake build doesn't check for pthreads

### ISSUE THREAD

**Issue by diizzyy** [PCRE2Project/pcre2#103]
Currently there's no check for pthreads which would be nice on UNIX systems at least

**Comment by carenas** [comment]
this is a "feature" of sorts, since it might block you from building with cmake where autotools is available and since that is the preferred way (as documented in the README)

any particular reason you wouldn't be able to use autotools instead in your environment?, cmake is mainly used in Windows AFAIK where this pthread checking is a non issue.

**Comment by diizzyy** [comment]
Sorry, I can't find any wording about preference so one would expect both to perform the same. While I don't have any issues with Autotools it would be nice if both worked as expected.

**Comment by jwsblokland** [comment]
@diizzyy It should be straightforward to add the additional package to CMake configuration. However, as far as I can tell none of the defined targets require pthreads but maybe I am missing something. Could you tell me which compiler and cmake options you have used?

**Comment by diizzyy** [comment]
@jwsblokland 
The only occurrence I seem to find is in src/sljit so you might be correct that it's not needed/used

**Comment by carenas** [comment]
> it's not needed/used

It is definitely needed/used (if jit is enabled in UNIX and as described in the README), but most linkers will be happy to build a DSO with unresolved symbols and those might even work if those symbols are resolved eventually when loading a binary.

with pthread being commonly embedded as part of the libc, and most systems dynamically solving those symbols at load time (except from memory in AIX or Cygwin) then I can see how it would not be easy to notice but that doesn't mean autotools shouldn't be still preferred.

**Comment by diizzyy** [comment]
Thanks! :-)
