### ISSUE TITLE
Unexpected error while building with `PCRE2GREP_SUPPORT_JIT` turned off and targeting 10.15

### ISSUE THREAD

**Issue by siegel** [PCRE2Project/pcre2#109]
Steps:

1. `ccmake .`
2. Change `CMAKE_OSX_DEPLOYMENT_TARGET` to `10.15`.
3. Change `PCRE2GREP_SUPPORT_JIT` to `OFF`.
4. press `c` to configure, then `g` to generate, then exit `ccmake`.
5. `make clean; make`

Expected:
-> successful build

Actual:
-> build fails, with error:
```
In file included from /Users/siegel/git/pcre2/src/sljit/sljitLir.c:275:
/Users/siegel/git/pcre2/src/sljit/sljitExecAllocator.c:156:2: error: "Must target Big Sur or newer"
```

It would appear that even when JIT is turned off, the sljit internals are getting compiled anyway. (I can't currently require macOS 11.0, which means that I can't currently enable JIT for all architectures. I suspect that the current state of affairs is related to [bug #2769 in the old tracker](https://bugs.exim.org/show_bug.cgi?id=2769) which appears to have never been resolved.)

**Comment by carenas** [comment]
> It would appear that even when JIT is turned off

To disable JIT you need to set the CMAKE_SUPPORT_JIT variable, the variable you changed disabled JIT only as part of the pcre2grep tool.

**Comment by PhilipHazel** [comment]
I'm closing this as dealt with.
