### ISSUE TITLE
brew install pcre2 502 error

### ISSUE THREAD

**Issue by qld-cf** [PCRE2Project/pcre2#117]
brew error, check this plz;

`
Downloading https://homebrew.bintray.com/bottles/pcre2-10.33.moja

curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "pcre2"
Download failed: https://homebrew.bintray.com/bottles/pcre2-10.33.mojave.bottle.tar.gz
`

**Comment by tmancill** [comment]
I am on monterey, not mojave, but the installation via `brew install pcre2` is successful on my system.  Since the error is a [502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502), I suspect a transient problem with bintray.com or Homebrew, but not with pcre2.

**Comment by PhilipHazel** [comment]
homebrew.bintray.com is nothing to do with the PCRE2 project so I'm closing this as invalid.
