### ISSUE TITLE
PCRE2_UTF flag detects U+202F as Mongolian

### ISSUE THREAD

**Issue by dAu6jARL** [PCRE2Project/pcre2#118]
if pcre2_compile() called with PCRE2_UTF option, U+202F(NARROW NO-BREAK SPACE) is detected as Mongolian.
pcre2grep with -u option occurs this error.

sample.text is as below.
```
foo bar (blank is U+0020)
foo​bar (blank is U+200B)
foo bar (blank is U+202F)
foo﻿bar (blank is U+FEFF)
```

command is as below.
```bash
pcre2grep -u '\p{Mongolian}' sample.text
```

output is as below.
```
foo bar (blank is U+202F)
```

**Comment by PhilipHazel** [comment]
It appears that Mongolian exists in the list of script extensions for U+202F. Here is output from the ucptest program:

$ ./ucptest 202f
U+202F CS  Separator: Space separator, common, Other, [latin, mongolian], [alphabetic, caseignorable, cased, diacritic, graphemebase, idcontinue, idstart, lowercase]

Perl also recognizes U+202F as Mongolian. The Unicode file ScriptExtensions.txt from which PCRE2 gets its data contains this:

# ================================================              
 
# Script_Extensions=Latn Mong                                
                                                             
202F          ; Latn Mong # Zs       NARROW NO-BREAK SPACE
                                  
# Total code points: 1
                                                  
# ================================================

So it looks like this is deliberate on the part of Unicode. I am therefore closing this as invalid.

**Comment by dAu6jARL** [comment]
Thank you for your reply.
I need to study more.

**Comment by PhilipHazel** [comment]
Note that \p{Mong} works like \p{scx:Mong}, that is, it checks both the script and the script extensions. If you want to test just the script, use \p{sc:Mong}.

**Comment by dAu6jARL** [comment]
Thank you for your advice. I'll use \p{sc:Xxx} as appropriate.
As it happened, I assumed U+202F as \p{Mongolian} in place name as follows.

Arrêt Nation – Voltaire [56]
https://foursquare.com/v/4ffc7038e4b07354de08b054

Pasta & Tapas Pietro 池袋店
https://foursquare.com/v/613eee8f90eb43793c2e76fd
