### ISSUE TITLE
Change Log info missing for latest tag'd release

### ISSUE THREAD

**Issue by jmbnyc** [PCRE2Project/pcre2#124]
Is there a change log for the latest tag version, .40?

**Comment by PhilipHazel** [comment]
The ChangeLog file is present in the tarballs and is also in the GitHub repo. Where else are you expecting it to be?

**Comment by jmbnyc** [comment]
Apologies, I was looking for ChangeLog file in the github repo and for some reason must have missed it, I see it now (perhaps I need another cup of coffee). I also checked here and did not see the 40 entry:
https://www.pcre.org/changelog.txt

Sorry for the bother.
