### ISSUE TITLE
Minor bug in CMakeLists.txt

### ISSUE THREAD

**Issue by deadlocklogic** [PCRE2Project/pcre2#125]
https://github.com/PCRE2Project/pcre2/blob/5271b533c4f77432e083b3c5f76b482d113eb9a6/CMakeLists.txt#L778
Should be `BUILD_SHARED_LIBS`, because it won't make sense this way.
Thanks.

**Comment by deadlocklogic** [comment]
Same goes for:
https://github.com/PCRE2Project/pcre2/blob/5271b533c4f77432e083b3c5f76b482d113eb9a6/CMakeLists.txt#L841
https://github.com/PCRE2Project/pcre2/blob/5271b533c4f77432e083b3c5f76b482d113eb9a6/CMakeLists.txt#L903
https://github.com/PCRE2Project/pcre2/blob/5271b533c4f77432e083b3c5f76b482d113eb9a6/CMakeLists.txt#L1103

**Comment by deadlocklogic** [comment]
Any chance to replace `INCLUDE_DIRECTORIES` with the newer/better `TARGET_INCLUDE_DIRECTORIES` in `cmake`?

**Comment by PhilipHazel** [comment]
Please take a look at issues #104 and #115. There is a proposal for a totally revised up-to-date new CMake config, but I do not know if this is progressing. I am loath to make any more changes to CMakeLists.txt at the moment. I rely entirely on the  CMake community for the CMake config.

**Comment by deadlocklogic** [comment]
Ok no worries, I was just trying to point out obvious bugs (maybe cause of copy pasting, and happens to all of us).
I will check the links for sure.
Thanks.

**Comment by wrowe** [comment]
Yes, this is a problem, the problematic lines (surely cut n' paste issues) all stem from this PR https://github.com/PCRE2Project/pcre2/commit/2410fbe3869cab403f02b94caa9ab37ee9f5854b

I'd ignore starting from scratch in issue #115 and follow the basic idea (simplify / streamline where ever possible) and go ahead, please do submit a PR, feel free to @ mention me and I'll even chip in a review. I noted this patch was full of unfinished changes, notably;

https://github.com/PCRE2Project/pcre2/commit/2410fbe3869cab403f02b94caa9ab37ee9f5854b#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR684-R690

It does appear the accepted and merged commit was never really tested.

**Comment by NWilson** [comment]
> Ok no worries, I was just trying to point out obvious bugs (maybe cause of copy pasting, and happens to all of us). I will check the links for sure. Thanks.
> 
> If you want I can submit a PR fixing these minor issues by the way. Just to point out this is trivially a bug:
> 
> [pcre2/CMakeLists.txt](https://github.com/PCRE2Project/pcre2/blob/5271b533c4f77432e083b3c5f76b482d113eb9a6/CMakeLists.txt#L775-L781)
> 
> Lines 775 to 781 in [5271b53](/PCRE2Project/pcre2/commit/5271b533c4f77432e083b3c5f76b482d113eb9a6)
> 
>    IF(BUILD_STATIC_LIBS) 
>      ADD_LIBRARY(pcre2-8 ALIAS pcre2-8-static) 
>      ADD_LIBRARY(pcre2-posix ALIAS pcre2-posix-static) 
>    ELSE(BUILD_STATIC_LIBS) 
>      ADD_LIBRARY(pcre2-8 ALIAS pcre2-8-shared) 
>      ADD_LIBRARY(pcre2-posix ALIAS pcre2-posix-shared) 
>    ENDIF(BUILD_STATIC_LIBS) 
> 
> No matter one's `CMake` proficiency. Maybe all the folks are statically linking anyway!
> And thanks again for your efforts.

Earlier in the week, I went back through the old historic CMake issues.

For the record (I realise this ticket is very old), the above reported "problem" is not actually a bug.

    IF(BUILD_STATIC_LIBS) 
      ADD_LIBRARY(pcre2-8 ALIAS pcre2-8-static) 
      ADD_LIBRARY(pcre2-posix ALIAS pcre2-posix-static) 
    ELSE(BUILD_STATIC_LIBS)
      ADD_LIBRARY(pcre2-8 ALIAS pcre2-8-shared) 
      ADD_LIBRARY(pcre2-posix ALIAS pcre2-posix-shared) 
    ENDIF(BUILD_STATIC_LIBS)

The `ELSE(comment)` and `ENDIF(comment)` syntax is an older CMake convention, equivalent to `ELSE() # comment`.

I think that deadlocklogic and wrowe above believed that this was an "elseif" expression.
