### ISSUE TITLE
Remove dependency on JIT in pcre2_compile.c

### ISSUE THREAD

**Issue by az-airtech** [PCRE2Project/pcre2#128]
Hi,

I have a hard requirement in a project to not use JIT. While there are CMake flags available (SUPPORT_JIT) available to effectuate this by configuration, the requirement is such that we do not even want to link with pcre2_jit_compile.c.o. 

This worked fine in the old PCRE2 repository of pcre2-10.36 that we used, but one necessary #ifdef SUPPORT_JIT disappeared in the current Github repository. Diff below. If there is no particular reason why this #ifdef disappeared, I would request to put it back.

```
diff --git a/src/pcre2_compile.c b/src/pcre2_compile.c
index d9eb7e5..3e4a44f 100644
--- a/src/pcre2_compile.c
+++ b/src/pcre2_compile.c
@@ -1266,9 +1266,10 @@ PCRE2_SIZE* ref_count;
 
 if (code != NULL)
   {
+#ifdef SUPPORT_JIT
   if (code->executable_jit != NULL)
     PRIV(jit_free)(code->executable_jit, &code->memctl);
-
+#endif
   if ((code->flags & PCRE2_DEREF_TABLES) != 0)
     {
     /* Decoded tables belong to the codes after deserialization, and they must

```
Arnoud.

**Comment by PhilipHazel** [comment]
I cannot see the code that you quote in the 10.36 tarball or indeed in an earlier one. Was this perhaps a local patch you made?
However, it seems a non-controversial patch; I will look in more detail in due course.

**Comment by az-airtech** [comment]
You are actually correct, I now found out. It is indeed a local patch,
which I was not initially aware of. Sorry for the confusion. If you could
look into it in due course and consider it non-controversial, that would be
much appreciated.

**Comment by PhilipHazel** [comment]
I have committed this patch so it will be in the next release, whenever that is.

**Comment by az-airtech** [comment]
Thank you!
