### ISSUE TITLE
pcre2grep should have an option to null-terminate filenames output with --files-with-matches and --files-without-match options

### ISSUE THREAD

**Issue by zsanter** [PCRE2Project/pcre2#137]
GNU `grep` has `-Z` and `--null`. `git grep` has `-z` and `--null`. However, neither support multiline PCRE matching.

I wanted to use this to detect files that don't end in a final newline, and pipe that into another command to remedy the situation.

Previously, my script only removed trailing whitespace and optionally replaced tabs with spaces, so `git grep` did the trick. The script is able to handle arbitrary filenames, and I'd like it to stay that way.

**Comment by PhilipHazel** [comment]
This should be straightforward to implement, and I will look into it once I have got some other work out of the way.

**Comment by PhilipHazel** [comment]
I have just committed a patch that implements -Z aka --null. It is intended to be much the same as GNU grep.
