### ISSUE TITLE
Add support for the RISC-V architecture

### ISSUE THREAD

**Issue by aaronfranke** [PCRE2Project/pcre2#14]
This is a low-priority feature request, but one that would make sense to be done eventually.

https://github.com/PhilipHazel/pcre2/tree/master/src/sljit

Based on the files in this folder, it seems that currently PCRE supports many architectures, including x86, ARM, PPC, MIPS, SPARC, and S390X. RISC-V is a new open source ISA supported by several Linux distros, and it would be nice if PCRE supported RISC-V.

Specifically, I am only interested in 64-bit RISC-V aka RV64 (32-bit and 128-bit exist too), and as for extensions, I recommend just supporting the general purpose extensions, so `-march=rv64g` (or `-march=rv64gc`). The abbreviation of RISC-V to just RV is very common and is the preferred option in some situations, so feel free to use that name.

**Comment by PhilipHazel** [comment]
Thank you for the comment. I will draw it to the attention of the JIT maintainer.

**Comment by zherczeg** [comment]
Supporting more cpus never hurt. Unfortunately I don't have much time lately, so this is unlikely happen in the close future.

**Comment by zherczeg** [comment]
There is an experimental risc-v support in the jit compiler now. It is only tested with qemu, so there might be cache flush issues.

**Comment by carenas** [comment]
Released with PCRE2 10.41

**Comment by ljavorsk** [comment]
@PhilipHazel Could you please confirm that the RISC-V is now JIT supported since 10.41? Thank you

**Comment by PhilipHazel** [comment]
I cannot confirm, but @zherczeg  will be able to.

**Comment by zherczeg** [comment]
I haven't tried it on real hw yet.

**Comment by ljavorsk** [comment]
I've built the new version on RISC-V Fedora builders and the pcre2-jit test passes, which I assume should test the JIT support.

**Comment by zherczeg** [comment]
This is great news! Thank you for the feedback.

**Comment by aaronfranke** [comment]
I haven't been able to test in Godot since we're unable to update PCRE2 for other reasons, but it sounds like everything is working great so I'll close this issue as completed. Thank you everyone!
