### ISSUE TITLE
Disable fork/exec on tvOS and watchOS

### ISSUE THREAD

**Issue by paulocoutinhox** [PCRE2Project/pcre2#140]
Hi,

On tvOS and watchOS we need disable fork/exec functions.

How can i do it?

https://github.com/conan-io/conan-center-index/issues/12182

Thanks.

**Comment by paulocoutinhox** [comment]
Is the same problem that was solved for poco:
https://github.com/pocoproject/poco/issues/3334

**Comment by PhilipHazel** [comment]
./configure  --disable-pcre2grep-callout-fork      disables the use of fork in pcre2grep.

**Comment by paulocoutinhox** [comment]
And for cmake, it make sense?
https://github.com/conan-io/conan-center-index/pull/12183/files

Resume for cmake:
`PCRE2GREP_SUPPORT_CALLOUT_FORK: ON or OFF`

**Comment by PhilipHazel** [comment]
Yes, you can disable it via CMake as well. I am going to close this issue.
