### ISSUE TITLE
Migration from Sourceforge is not complete

### ISSUE THREAD

**Issue by Neustradamus** [PCRE2Project/pcre2#154]
Dear @PCRE2Project, @PhilipHazel,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/projects/pcre/

To change informations, go here: https://sourceforge.net/p/pcre/admin/overview

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/pcre/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/pcre/admin/overview
- A new tab, go here: https://sourceforge.net/projects/pcre/

Thanks in advance.

**Comment by zherczeg** [comment]
Actually the sourceforge code is a mirror maintained by a user called mish_the_fish. So pcre is never migrated from there.

**Comment by PhilipHazel** [comment]
That's right. This project does not manage the sourceforce site, so I'm closing this issue as invalid.

**Comment by Neustradamus** [comment]
@zherczeg, @PhilipHazel: Can you contact directly Andrew Ho?
- https://sourceforge.net/u/mish_the_fish

I have published issue here too:
- https://sourceforge.net/p/pcre/feature-requests/36/

It is possible to update the Website too?
- http://www.pcre.org/

Thanks in advance.

**Comment by Neustradamus** [comment]
@PhilipHazel: Any news on it?

**Comment by PhilipHazel** [comment]
Andrew Ho is not contactable.

**Comment by Neustradamus** [comment]
Dear @andrewgho,

I have found you on GitHub :)

I have sent you message with Sourceforge form, and by e-mail too about the PCRE Sourceforge project.

Thanks in advance.
