### ISSUE TITLE
Line comment bug

### ISSUE THREAD

**Issue by Adrian-Hawryluk** [PCRE2Project/pcre2#155]
So I was making a big ass regex for use in AHK and it wasn't working.  Seems that the line comment (`# ...`) has a bug.  Using the `x` mode with LFs as a EOL marker, this regex worked:
```
	a
	# comment before error
	(
```
When obviously it should have had a parse error.  Changing the EOL line marker to CRLF did seem to resolve the issue as did converting the line comment to an embedded (`(?# ...)`) comment.

According to the [ahk change log](https://www.autohotkey.com/docs/AHKL_ChangeLog.htm), it's using version 8.30 (search for text `PCRE`).

**Comment by PhilipHazel** [comment]
I don't know what AHK is, but if it's using 8.30 it is relying on an unmaintained, obsolete PCRE1 release that was released in 2012. The final PCRE1 release is 8.45 (2021) - there is no more maintenance. PCRE development is now entirely on PCRE2, so we need evidence of something not working in PCRE2 (current release 10.40), preferably as a regex/subject pair that doesn't do what you expect, before any investigation of a possible bug will happen. (Even more preferably as a pcre2test input file.)

**Comment by Adrian-Hawryluk** [comment]
Never mind.  It was explained to me that the switch to set what pcre uses to match a newline actually also affects the regex itself.  It is apparently not so much of a bug but a feature. 🙄 🤣
