### ISSUE TITLE
pcre2grep does not set PCRE2_UCP

### ISSUE THREAD

**Issue by klpn** [PCRE2Project/pcre2#185]
When `pcre2grep` is called with `-u`, the flag `PCRE2_UCP` is not set, see:
<https://github.com/PCRE2Project/pcre2/blob/0746b3d523c9a799aa62ae9e03188b23664f48b0/src/pcre2grep.c#L3607>

This leads to incorrect behavior with boundary matches and non-ASCII letters, such as:
```
$  echo 'Öm' | pcre2grep -u '\bm'
Öm
```
The output should be nothing. Adding the `PCRE2_UCP`flag fixes the problem:
```c
  case 'u': options |= PCRE2_UTF|PCRE2_UCP; utf = TRUE; break;
```
GNU grep with the `-P` option also behaves incorrectly in this case, unlike perl (see this [Twitter thread](https://twitter.com/gro_tsen/status/1610972356972875777) for more examples and discussion).

**Comment by zherczeg** [comment]
I think this change is reasonable, However, we don't know who depends on the current behaviour. Anyway pcre2grep is just an example code, not intended for use in production.

**Comment by klpn** [comment]
Yes. And if the flag added for the `-u` option, the `-U` option should probably also be updated accordingly.

**Comment by klpn** [comment]
This issue was noticed by GNU grep team, and has been [patched there](https://lists.gnu.org/archive/html/bug-grep/2023-01/msg00011.html).

**Comment by zherczeg** [comment]
I would not call it an issue, more of a feature request. The proper change probably needs an option to go back to the old mode as well.

**Comment by PhilipHazel** [comment]
Yes indeed. I am always wary about making incompatible changes, however "obvious" they may be. In this case, I agree that it's probably best to make it the default - especially as that's what others do - but I will not be surprised if it catches out at least one person. I will look at this in due course and include something like --utf-no-ucp.

**Comment by carenas** [comment]
Looking at the performance impact of this change, was wondering if we would need to at least introduce an equivalent to the `/a` modifier as well.

**Comment by PhilipHazel** [comment]
There are now (in HEAD) some new options for restricting various things to ASCII and disabling Unicode/ASCII case folding. I will now consider how best to use these in pcre2grep.

**Comment by PhilipHazel** [comment]
I have now updated pcre2grep in HEAD. Both -u and -U set PCRE2_UCP by default, but there is a --no-ucp option to disable this. There is also a --case-restrict option which sets PCRE2_EXTRA_CASELESS_RESTRICT. Finer control is now available via the new options settings within patterns, e.g. (?aD) to force \d to ASCII while leaving \s and \w as Unicode.
