### ISSUE TITLE
the negtive lookahead and negtive lookbehind seems not supported.

### ISSUE THREAD

**Issue by JohnHerry** [PCRE2Project/pcre2#211]
Thanks for the good job.
    I am a pythoner trying to convert my python program into C++, I found that my regulare strings with negtive lookahead or negtive lookbehind will match just like the "negtive lookahead" and "negtive lookbehind" part are not exist.

eg.
    my regure string is “(?<![a-zA-Z0-9])(H2O|Covid\-19|Windows)(?![a-zA-Z0-9])”
    
   In my expection, it will match when input string is "My Computer runs Windows 12",  but not "this is Windows10" or "AWindows is my program".

   But, in my test, all the three are matched out the keyword "Windows",   I donot know why. Is there any compile options in PCRE2 to open/close  lookahead/lookbehind?

**Comment by ltrzesniewski** [comment]
> In my expection, it will match when input string is "My Computer runs Windows 12", but not "this is Windows10" or "AWindows is my program".

Your expectation is correct, see the test here: https://regex101.com/r/34P16P/1

> But, in my test, all the three are matched out the keyword "Windows", I donot know why. Is there any compile options in PCRE2 to open/close lookahead/lookbehind?

There's no option to disable lookarounds. I suppose you must have made a mistake in your program somewhere.
