### ISSUE TITLE
10.42 and 10.41 breaking metalog

### ISSUE THREAD

**Issue by Massimo-B** [PCRE2Project/pcre2#214]
I'm a user of metalog. Coming from https://github.com/hvisage/metalog/issues/19 we found that pcre2-10.41 and 10.42 are breaking metalog creating unusual / subdirs:
```
drwx------   1 root root   34 13. Feb 08:41 ''$'\360''!'$'\220''1'$'\324\177'/
drwx------   1 root root   34 13. Feb 13:28 ''$'\300''!'$'\220''1'$'\324\177'/
drwx------   1 root root   34  8. Feb 10:14 ''$'\300\361''#3M'$'\177'/
drwx------   1 root root   34 10. Feb 07:38 ''$'\360''!~5'$'\264\177'/
drwx------   1 root root   34 10. Feb 08:13 ''$'\300''!~5'$'\264\177'/
```
Not sure it this is a bug on pcre2 or metalog, but downgrading to 10.40 solves the issue.
I know this is not the best error description for your library. Do you have any idea, based on the changes in 10.41 and 10.42, what could have caused this issue?
Thanks.

**Comment by PhilipHazel** [comment]
No functions in the PCRE2 library create files or directories, so although nothing can ever be ruled out, I can't think how PCRE2 could be involved.

**Comment by Massimo-B** [comment]
The issue was probably found in https://github.com/hvisage/metalog/issues/19#issuecomment-1461921677.
Sorry for bothering, can be closed here.
