### ISSUE TITLE
terminate options ( -- ) produces error (pcre2grep)

### ISSUE THREAD

**Issue by atomGit** [PCRE2Project/pcre2#215]
pcre2grep version 10.42 2022-12-11

```bash
$ printf 'this' > file
$ pcre2grep 'this' -- file
pcre2grep: Failed to open --: No such file or directory
file:this
```

**Comment by carenas** [comment]
Isn't this working as expected?; 'this' is not an option and `--` would indicate the end of options if it where, ex:

```
$ pcre2grep -e this -- file
```

using the original syntax you indicate to search from the pattern `'this'` inside the files `--` and `file`

**Comment by atomGit** [comment]
yes, it is working as expected - i was sure i was missing something stupid simple but i didn't know what
