### ISSUE TITLE
PCRE2 compatable with ARM Ubuntu, or Raspberry Pi 4

### ISSUE THREAD

**Issue by Danrancan** [PCRE2Project/pcre2#220]
I am trying to compile the Modsecurity Connector module, and it requires PCRE2 running Ubuntu 20.04 server on Raspberry Pi 4. When I try to configure the connector module i get:
`configure: PCRE2 library was not found`
There don't seem to be any Ubuntu ARM packages that fullfill this request. So is there any way for me to get the PCRE2 Library onto my Raspberry Pi Ubuntu Server so I can compile that module? If there is no binary, then is it possible to compile an arm library on my Ubuntu Server for the Raspberry pi? Any help, tips, or advice appreciated in advance.

**Comment by PhilipHazel** [comment]
PCRE2 is just a set of standard C code. Assuming you have a C compiler and library on your Pi you should be able to compile it.
Download the tarball of the latest release from GitHub and read the README.

**Comment by JetXujing** [comment]
`configure: PCRE2 library was not found`
Generally, this type of problem is not related to the corresponding package. You only need to install the corresponding package. If no package is available, you need to compile the package. If the compilation is faulty, the compatibility problem may be caused.

**Comment by zherczeg** [comment]
The comment above still stands. Compile it manually form git / tarball.

**Comment by BrianInglis** [comment]
> I am trying to compile the Modsecurity Connector module, and it requires PCRE2 running Ubuntu 20.04 server on Raspberry Pi 4. When I try to configure the connector module i get: `configure: PCRE2 library was not found` There don't seem to be any Ubuntu ARM packages that fullfill this request. So is there any way for me to get the PCRE2 Library onto my Raspberry Pi Ubuntu Server so I can compile that module? If there is no binary, then is it possible to compile an arm library on my Ubuntu Server for the Raspberry pi? Any help, tips, or advice appreciated in advance.

You need to install the *PCRE2* development library `libpcre2-dev` which is available for arch `armhf` from repo `focal-updates` on your preferred local *Ubuntu* mirror; you may also want to install utilities package `pcre2-utils`. 
Development library packages contain the package config files, scripts, source headers, debug libraries, library docs and API man pages, required to build programs with this [library](https://packages.ubuntu.com/focal-updates/armhf/libpcre2-dev/filelist).

**Comment by PhilipHazel** [comment]
I am closing this issue as it seems to be resolved.
