### ISSUE TITLE
(?R) doesn't seem to meet expectations

### ISSUE THREAD

**Issue by JetXujing** [PCRE2Project/pcre2#240]
```
[root@localhost ~]# cat re
/(a(?R)b)/
    aabb
[root@localhost ~]# pcre2test re
PCRE2 version 10.39 2021-10-29
/(a(?R)b)/
    aabb
No match
[root@localhost ~]#
```
I tested it at 10.39 and I don't have the latest version of pcre2, maybe the latest version has fixed it.. From what I understand, this should match.

As I understand it, the regular expression `/(a(?R)b)/` means matching a nested string that starts with `a` and ends with `b`, and can have `a` and `b` in between. For the string `aabb`, it conforms to the above description because it can be decomposed into two substrings `a` and `abb`, where the second substring contains a nested substring `ab`, and therefore the matching succeeds.

**Comment by zherczeg** [comment]
https://regex101.com/r/FbLcN6/1
I don't think your pattern matches anything. The (?R) creates an infinite loop.

Just add a terminating "empty" match: `/(a(?:(?R)|)b)/`
