### ISSUE TITLE
Declaring named capture groups

### ISSUE THREAD

**Issue by elfring** [PCRE2Project/pcre2#25]
[Named capture groups](https://github.com/PhilipHazel/pcre2/blob/8f3e11a355b2dfc362151bf2a2ba2ab21d6d58a4/doc/html/pcre2syntax.html#L443 "Documentation") are supported for a while.
How do you think about a software extension for the possibility to declare the binding of regular expressions to identifiers before such identifiers would be reused at other places?

**Comment by elfring** [comment]
I would appreciate improved descriptions for [the mentioned functionality](https://philiphazel.github.io/pcre2/doc/html/pcre2syntax.html#SEC24 "Documentation for conditional patterns") according to desirable pattern definitions.

**Comment by elfring** [comment]
* May patterns be declared or defined in multiple lines?
* Would any extra white-space characters influence subsequent pattern matching in undesirable ways?

**Comment by zherczeg** [comment]
With `/x`, `(?x:)`, `PCRE2_EXTENDED` you can ignore spaces in the pattern, and even comments can be added. Inside `(DEFINE)`, or `(?:){0}` everything is ignored. The only way to use something inside a `(DEFINE)` is recursion.

**Comment by elfring** [comment]
Thanks for [your link to another provided test case](https://github.com/PhilipHazel/pcre2/blob/2410fbe3869cab403f02b94caa9ab37ee9f5854b/testdata/testinput1#L5898 "Checking pattern definitions").

:crystal_ball: How will the chances evolve to improve the documentation any further also for this software area?

**Comment by PhilipHazel** [comment]
PCRE2 documentation is not really the place for tutorials. For discussion of (?(DEFINE)  see this web site:

https://www.regular-expressions.info/subroutine.html

**Comment by elfring** [comment]
>PCRE2 documentation is not really the place for tutorials.

:thought_balloon: I hope that this information source can become better and more complete (also in comparison to the other good information source which you mentioned).
