### ISSUE TITLE
commit required to match UCP \b \w in grep 3.11

### ISSUE THREAD

**Issue by BrianInglis** [PCRE2Project/pcre2#254]
[Announcement](https://savannah.gnu.org/news/?id=10364) for `grep` 3.11 says:
> This release makes PCRE patterns like [\d] work again, at the expense of
> reverting to the behavior of grep 3.8, in that patterns like \w and \b go
> back to using ASCII rather than Unicode interpretations.  However, if you
> build grep using pcre2 newer than 10.42, then \w and \b do work properly.

Which *PCRE2* commit is required for `libpcre2-dev{,el}` to build `grep` so \b and \w do work properly with Unicode text?

**Comment by PhilipHazel** [comment]
Possibly a608946 (Additional PCRE2_EXTRA_ASCII_xxx code, 2023-02-01)

**Comment by BrianInglis** [comment]
Cheers thanks!
