### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by jpelletier** [PCRE2Project/pcre2#255]
libtool: install: /usr/bin/install -c .libs/libpcre2-8.lai /usr/local/lib/libpcre2-8.la
libtool: warning: relinking 'libpcre2-posix.la'
libtool: install: (cd /home/public/temp/bpi-iot-ros-ai/pcre2-10.42; /bin/bash "/home/public/temp/bpi-iot-ros-ai/pcre2-10.42/libtool"  --silent --tag CC --mode=relink gcc -DPCRE2_CODE_UNIT_WIDTH=8 -fvisibility=hidden -O2 -version-info 3:4:0 -o libpcre2-posix.la -rpath /usr/local/lib src/libpcre2_posix_la-pcre2posix.lo libpcre2-8.la )
mv: cannot move 'libpcre2-posix.so.3.0.4' to 'libpcre2-posix.so.3.0.4U': Permission denied
libtool:   error: error: relink 'libpcre2-posix.la' with the above command before installing it
Makefile:1567: recipe for target 'install-libLTLIBRARIES' failed

**Comment by jpelletier** [comment]
I uncompressed the package in /usr/local/src
Went super user,
did ./configure, make, make install
It worked!

**Comment by PhilipHazel** [comment]
Tidying up; closing.
