### ISSUE TITLE
Inconsistent behaviour for NULL zero length strings

### ISSUE THREAD

**Issue by jagprog5** [PCRE2Project/pcre2#270]
Commit 4ef0c51d2bbe1c572840cbb14c3080b1192e83d2 fixed this issue for substitution and matching, however [pcre2_compile on latest](https://github.com/PCRE2Project/pcre2/blob/fb84d7399181161ad8074ee26778007dfcbccd5b/src/pcre2_compile.c#L9973) still treats a null argument with zero length as an error.

The same fix should be applied to pcre2_compile, as I don't think this should generate an error.

**Comment by carenas** [comment]
Do you have a use case where this will be required, or is just for consistency?

Note that, unlike the other cases, there is syntactical differences, as the empty pattern ("") that would be used would match ALL subjects, and a NULL pattern was never considered valid (ex: regcomp would segfault, while we will return an error instead)

**Comment by jagprog5** [comment]
I have a specific use case:

In my project, this [test case](https://github.com/jagprog5/choose/blob/744b83cc6887eeef1dfef051584a95071d7b9736/src/test.cpp#L586) was failing. See my associated band-aid fix [here](https://github.com/jagprog5/choose/blob/744b83cc6887eeef1dfef051584a95071d7b9736/src/regex.hpp#L32).

Pre-refactor, the test case passes a zero length null terminating string that points to the pattern. This calls pcre2_compile with non-null pointer pattern, and length PCRE2_ZERO_TERMINATED. It is handled correctly.

Post-refactor, the test case passes a pointer to an empty vector containing the pattern. This calls pcre2_compile with null pointer pattern and length 0. It throws an error.

In either case, both were holding the same data. One contained in a c-string, the other in a vector\<char\>, both empty. These two cases should be treated the same, but they are not.

**Comment by jagprog5** [comment]
Friendly ping!

I'd like to [quote](https://github.com/PCRE2Project/pcre2/blob/4ef0c51d2bbe1c572840cbb14c3080b1192e83d2/ChangeLog#L40) @PhilipHazel from the commit I mentioned above:

> Apparently a number of applications treat NULL/0 in this way.

I feel that my use case cleanly aligns with this same reasoning. That being said, you mentioned outside context; I don't know the specifics of regcomp, and I don't know if there is a considerable user-base that expects this specific behavior. From my point of view it doesn't make sense, but I'm not special.

Please let me know either way.

**Comment by PhilipHazel** [comment]
I have no problem with this; I've just been busy with other things recently. At some point I will implement it.

**Comment by PhilipHazel** [comment]
HEAD now supports this. It took longer to invent a way of testing it than to make the change - oops, just remembered I haven't updated the pcre2test doc. Will do so right now.
