### ISSUE TITLE
Segfault in pcre2_jit_match for MSYS2 and CYGWIN

### ISSUE THREAD

**Issue by kyle-sylvestre** [PCRE2Project/pcre2#272]
_WIN64 is not defined for MSYS2 and CYGWIN.
This leads to using the linux x64 ABI instead of windows x64, thus crashing on the difference of calling convention. (see sljitNativeX86_common.c line 91, pcre2 version 10.42)

**Comment by carenas** [comment]
> _WIN64 is not defined for MSYS2 and CYGWIN.

I believe that is only a part of the problem and a full solution will need to be implemented first in upstream [SLJIT](/zherczeg/sljit.git)

meanwhile, if you want a working JIT in Windows should use MSVC or 32bit MingW64 AFAIK

**Comment by kyle-sylvestre** [comment]
I'll stick with MinGW then, thanks for the info
