### ISSUE TITLE
Arm64 crash on JIT call to incorrect address

### ISSUE THREAD

**Issue by sebpop** [PCRE2Project/pcre2#276]
On arm64, JIT generated code crashes when executing a call to a function with an address + an incorrect offset `-0x10000000 = 2^26 (base 10)`.

The jit code contains several other calls to the same function address without the incorrect offset:

```
   0xffffa10a6298:      mov     x9, #0x67a8
   0xffffa10a629c:      movk    x9, #0xa90a, lsl #16
   0xffffa10a62a0:      movk    x9, #0xffff, lsl #32
   0xffffa10a62a4:      blr     x9               // correct address
[...]
   0xffffa10a67a4:      bl      0xffff990a67a8   // this is incorrectly offset by -0x10000000
                                                 // crashes when this call executes.
[...]
   0xffffa10a6840:      bl      0xffffa90a67a8   // correct address
[...]
      // several other calls with the correct address.
```

I do not know where the incorrect offset is coming from.

I have seen that when sljit generates a call to a function, sljit uses an offset `SLJIT_IMM()`.
For example the doc for `sljit_emit_icall` says:
https://github.com/PCRE2Project/pcre2/blob/master/src/sljit/sljitLir.h#L1540
```
/* Emit a C compiler (ABI) compatible function call.
Direct form: set src to SLJIT_IMM() and srcw to the address
```
Is there a way for SLJIT_IMM to be modified during the jit compilation, or is that an immutable immediate constant?
```
src/sljit/sljitLir.h:#define SLJIT_IMM          0x40
```
If SLJIT_IMM does not change, then the incorrect offset can only be part of srcw address computation.

**Comment by zherczeg** [comment]
SLJIT_IMM is a constant, since it represents an immedate value. Probably the compiler tries to optimize the call with a bl instruction and doing it wrong during the executable code generation.

https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitNativeARM_64.c#L187

**Comment by sebpop** [comment]
In `detect_jump_type` I see that `executable_offset` is directly used in an add then a sub: https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitNativeARM_64.c#L201
and this without going through the usual macro as in the rest of the code.  Shouldn't this line be written:
```
target_addr = (sljit_uw)(SLJIT_ADD_EXEC_OFFSET(code, executable_offset) + jump->u.label->size);
```
In 27eab0b83688f20b3b8282b6a31e8a54bbada17e I see the same pattern in other targets: Arm32, Arm64, MIPS, PPC, SPARC.

**Comment by zherczeg** [comment]
`executable_offset = SLJIT_EXEC_OFFSET(code);`
Probably adding the macro could be used as an optimization, but should not be the issue.

Since `-0x10000000` is `-0x8000000 << 1` something might be wrong with this compare:
`if (diff <= 0x7ffffff && diff >= -0x8000000) {`

It should check the 28 bit signed immedate offset:
`bits(64) offset = SignExtend(imm26:'00', 64);`

**Comment by ilink-splunk** [comment]
Here's the MR: https://github.com/PCRE2Project/pcre2/pull/277
About a year worth of debugging on and off, down to a 1 character change :)

**Comment by zherczeg** [comment]
Thank you very much! The jit compiler related fixes should go to its own repository, which is migrated back to pcre2 later:
https://github.com/zherczeg/sljit

**Comment by sebpop** [comment]
There's a similar computation in ARM32.
@zherczeg maybe that code needs to be fixed as well:
```
--- a/src/sljit/sljitNativeARM_32.c
+++ b/src/sljit/sljitNativeARM_32.c
@@ -427,10 +427,10 @@ static SLJIT_INLINE sljit_s32 detect_jump_type(struct sljit_jump *jump, sljit_uw
                code_ptr--;
 
        if (jump->flags & JUMP_ADDR)
-               diff = ((sljit_sw)jump->u.target - (sljit_sw)(code_ptr + 2) - executable_offset);
+               diff = ((sljit_sw)jump->u.target - (sljit_sw)(code_ptr - 2) - executable_offset);
        else {
                SLJIT_ASSERT(jump->flags & JUMP_LABEL);
-               diff = ((sljit_sw)(code + jump->u.label->size) - (sljit_sw)(code_ptr + 2));
+               diff = ((sljit_sw)(code + jump->u.label->size) - (sljit_sw)(code_ptr - 2));
        }
 
        /* Branch to Thumb code has not been optimized yet. */

```

**Comment by ilink-splunk** [comment]
https://github.com/zherczeg/sljit/pull/177 here's the new MR

**Comment by zherczeg** [comment]
The compiler is migrated into PCRE2

**Comment by ilink-splunk** [comment]
Great, thank you!
