### ISSUE TITLE
For big regex JIT compiler is returning PCRE2_ERROR_NOMEMORY 

### ISSUE THREAD

**Issue by paragikjain** [PCRE2Project/pcre2#283]
1. For big regex JIT compiler is returning PCRE2_ERROR_NOMEMORY, how can I handle this, is there any way to increase max memory limit used during JIT compilation.  

2. In the process of establishing the general context, we provide a memory allocation function. I've included additional print logs within this function. If the JIT compilation function utilizes the same memory allocation function for its own memory needs, I should be able to observe the print logs that I've inserted. However, if the JIT compilation function doesn't perform any memory allocation itself, it raises the question of why we're still encountering failures indicated by the "PCRE2_ERROR_NOMEMORY" error code.

**Comment by PhilipHazel** [comment]
Have you read the JIT documentation in pcre2jit.3?

**Comment by zherczeg** [comment]
Depends on where it is thrown. If malloc is the problem, it cannot be helped.

This line also throws a memory error here:
https://github.com/PCRE2Project/pcre2/blob/master/src/pcre2_jit_compile.c#L14175

This is the stack space allocated for the jit code. Now it can be raised to 1Mbyte, which is 16 times more than the 64K there.
