### ISSUE TITLE
A\z matches on A<invalid-UTF8>B with PCRE2_UTF|PCRE2_MATCH_INVALID_UTF and no-JIT

### ISSUE THREAD

**Issue by stephane-chazelas** [PCRE2Project/pcre2#343]
```
$ printf 'A\200B\n' | pcre2grep --no-jit -qU 'A\z' && echo match
match
```

(unexpected as the subject doesn't end in `A`).

That doesn't happen when `pcre2grep` is built with JIT support (`--enable-jit`) and without that `--no-jit`.

It doesn't happen with `$` in place of `\z`.

Initially found in https://github.com/raforg/rawhide/issues/2

Reproduced with pcre2 10.42 on Debian GNU/Linux amd64 sid/unstable.

**Comment by PhilipHazel** [comment]
Thanks for the report. Fixed in 05206d6.

**Comment by addisoncrump** [comment]
This change is incomplete for noteol:
```
$ ./pcre2test -jit
PCRE2 version 10.43-DEV 2023-04-14 (8-bit)
  re> /a\z/    
data> a
 0: a
data> a\=noteol
 0: a
data> a\=no_jit
 0: a
data> a\=no_jit,noteol
No match
```

Maybe a JIT issue?

**Comment by zherczeg** [comment]
Why? pcre2.txt says:

PCRE2_NOTEOL
This option affects only the behaviour of the dollar metacharacter. It does not affect \Z or \z.

**Comment by PhilipHazel** [comment]
You are quite right. I should have read my own documentation! I will fix this.
