### ISSUE TITLE
Confusion about `pcre2_substring_list_free()` calling; documentation/prototype problem?

### ISSUE THREAD

**Issue by siegel** [PCRE2Project/pcre2#345]
I've got some code that looks like this:

```c
PCRE2_UCHAR	**captureStrings = NULL;
PCRE2_SIZE	*captureStringLengths = NULL;

if (0 == pcre2_substring_list_get(matchData, &captureStrings, &captureStringLengths))
{
	//	...do some work here...
	
	pcre2_substring_list_free(captureStrings);  // <-- error on this line
}

```

The documentation and prototype for `pcre2_substring_list_free()` say that it accepts a single `PCRE_SPTR *` argument, which doesn't make a lot of sense to me; and I get an error from the compiler on the call to `pcre2_substring_list_free()` when passing the strings block returned from a successful call to `pcre2_substring_list_get()`.

Reading the implementations of `pcre2_substring_list_get()` and `pcre2_substring_list_free()` at `pcresubstring.c:448` it sure seems as though it's expecting the argument to be the same thing that came back from `pcre2_substring_list_get()`. 

What obvious thing am I missing here, and is there a way that the documentation could be clarified, or could the prototype be changed so that a cast isn't necessary?

**Comment by PhilipHazel** [comment]
I don't think we can change the prototype because it's been out there for many years now, and indeed seems to have been copied from PCRE1. I can try to clarify the documentation.

**Comment by MatthewVernon** [comment]
...should this warrant a soname bump for the next release, then?

**Comment by MatthewVernon** [comment]
I have long since forgotten much of what I knew about this, but a friendly local IRC channel was of the view that _if_ the underlying code change is equivalent to `unsigned char **` => `const unsigned char **` then that's not an ABI change, so does not need a soname increase.
