### ISSUE TITLE
Inconsistency with ungreedy unset backrefs

### ISSUE THREAD

**Issue by addisoncrump** [PCRE2Project/pcre2#349]
I cannot find a version for which the behaviour is consistent, so I assume this bug has been around since the JIT compiler.

```
  re> /\1+?()/match_unset_backref
data> a
No match
data> a\=no_jit
 0: 
 1: 
```

In this case I believe the JIT is wrong, as ungreedy here should just be 1 match of empty.

**Comment by zherczeg** [comment]
Fixed in 9de4d53cf850e0fca625ce9d80c12bea5b2a5ab9
