### ISSUE TITLE
Inconsistency with * or ? followed by \x{ffffffff} when caseless,ucp

### ISSUE THREAD

**Issue by addisoncrump** [PCRE2Project/pcre2#351]
I confirmed this is unrelated to the changes applied in #350 -- this has been around since at least 10.40, but did not check before that version.

Consider the following regexes:
```
$ ./pcre2test -jit -32
PCRE2 version 10.43-DEV 2023-04-14 (32-bit)
  re> /a*\x{ffffffff}/caseless,ucp
data> \x{ffffffff}
 0: \x{ffffffff}
data> \x{ffffffff}\=no_jit
 0: \x{ffffffff}
data> 
  re> /k*\x{ffffffff}/caseless,ucp
data> \x{ffffffff}
 0: \x{ffffffff}
data> \x{ffffffff}\=no_jit
No match
```

It seems that the case-folded `k` has different behaviour to the case-folded `a`. Note that using e.g. `b` or `\x{ff000000}` in place of `\x{ffffffff}` does not exhibit the same behaviour:

```
  re> /k*\x{ff000000}/caseless,ucp
data> \x{ff000000}
 0: \x{ff000000}
data> \x{ff000000}\=no_jit
 0: \x{ff000000}
```

Nor does this issue appear standalone:

```
  re> /\x{ffffffff}/caseless,ucp
data> \x{ffffffff}
 0: \x{ffffffff}
data> \x{ffffffff}\=no_jit
 0: \x{ffffffff}
```

The issue also appears with 0-or-1 repetitions:

```
  re> /k?\x{ffffffff}/caseless,ucp
data> \x{ffffffff}
 0: \x{ffffffff}
data> \x{ffffffff}\=no_jit
No match
```

**Comment by PhilipHazel** [comment]
This is now fixed in ad73148.
