### ISSUE TITLE
Escaped characters in subsitution replacement not working

### ISSUE THREAD

**Issue by jagprog5** [PCRE2Project/pcre2#354]
```c++
#include <stdio.h>
#define PCRE2_CODE_UNIT_WIDTH 8
#include <pcre2.h>
#include <cstring>

int main() {
    const PCRE2_SPTR8 subject = (PCRE2_SPTR8)"abcd";
    const PCRE2_SPTR8 pattern = (PCRE2_SPTR8)".+";
    const PCRE2_SPTR8 replacement = (PCRE2_SPTR8)"$0\\x77";

    PCRE2_SIZE error_offset;
    int error_code;

    pcre2_code *re = pcre2_compile((PCRE2_SPTR8)pattern, PCRE2_ZERO_TERMINATED, 0, &error_code, &error_offset, NULL);
    if (re == NULL) {
        PCRE2_UCHAR buffer[256];
        pcre2_get_error_message(error_code, buffer, sizeof(buffer));
        printf("PCRE2 compilation failed at offset %d: %s\n", (int)error_offset, buffer);
        return 1;
    }

    pcre2_match_data *match_data = pcre2_match_data_create_from_pattern(re, NULL);

    size_t output_length = 1000;
    PCRE2_UCHAR *output = (PCRE2_UCHAR *)malloc(output_length * sizeof(PCRE2_UCHAR));
    int rc = pcre2_substitute(re, subject, PCRE2_ZERO_TERMINATED, 0, 0, match_data, NULL, replacement, PCRE2_ZERO_TERMINATED, output, &output_length);

    puts((char*)output);

    return 0;
}
```

Version 10.42
Subject: `abcd`
Pattern: `.*`
Replacement: `$0\x77`

Output: `abcd\x77`
Desired output: `abcdw` (like [here](https://regex101.com/r/WLJhOD/))

Am I missing something? I assume normal pcre2 synax including that for [escape characters](https://www.pcre.org/current/doc/html/pcre2syntax.html#SEC3) would apply to the replacement syntax as well, since I don't see [anything](https://www.pcre.org/current/doc/html/pcre2_substitute.html) that says otherwise.

Thanks.

**Comment by PhilipHazel** [comment]
I am afraid you are wrong. The syntax to which you are referring is the _pattern_ syntax. It does not apply to substitution strings. The documentation in pcre2api says this: "If PCRE2_SUBSTITUTE_LITERAL is set, the replacement string is not interpreted
in any way. By default, however, a dollar character is an escape character that can specify the insertion of characters from capture groups and names from (*MARK) or other control verbs in the pattern." It then goes on to talk about dollar substitutions. I agree that it doesn't say backslash is not interpreted, but equally, it doesn't say that it is. I have added an explicit statement that dollar is the only escape character.
