### ISSUE TITLE
Regression issue introduced by ce5b604

### ISSUE THREAD

**Issue by JetXujing** [PCRE2Project/pcre2#362]
The problem is caused by ce5b604ebf7bf8fdd46b3026e19e1ea4792ca3a7. To reproduce the problem, perform the following steps:
1. touch test
```
[root@localhost ~]# cat test
/|a(?0)b/endanchored
    ab
```
2. pcre2test -q -8 test
3. pcre2test -q -8 -jit test

The result before ce5b604ebf7bf8fdd46b3026e19e1ea4792ca3a7 is merged is as follows:
```
[root@localhost ~]# pcre2test -q -8 test
/|a(?0)b/endanchored
    ab
 0: ab
[root@localhost ~]# pcre2test -q -8 -jit test
/|a(?0)b/endanchored
    ab
 0: ab
```

The result after ce5b604ebf7bf8fdd46b3026e19e1ea4792ca3a7 is merged is as follows:
```
[root@localhost ~]# pcre2test -q -8 test
/|a(?0)b/endanchored
    ab
 0:
[root@localhost ~]# pcre2test -q -8 -jit test
/|a(?0)b/endanchored
    ab
 0: ab
```

**Comment by PhilipHazel** [comment]
I cannot reproduce this with the latest HEAD:

$ ./pcre2test -q -8 zz
/|a(?0)b/endanchored
    ab
 0: ab

Have you tried the latest HEAD? The commit you mentioned was, I think, the first fix I tried, which was wrong, later removed, and superseded by 86919c9.

**Comment by JetXujing** [comment]
Thank you for your reply. I am not using the latest head. I will try to use 86919c9 for verification.

**Comment by JetXujing** [comment]
I find that fdfbcd9f5aad1006cc5eaa7889a7aa43a5f06aba has rolled back the previous submission. Close the issue.
