### ISSUE TITLE
Malformed pcre2demo(3) man page destroys apropos readability

### ISSUE THREAD

**Issue by kevtan** [PCRE2Project/pcre2#368]
Currently, it looks like the entire text of the man page is placed under the NAME section. This can also be seen from the (auto-generated) source code: https://github.com/PCRE2Project/pcre2/blob/master/doc/pcre2demo.3

Would it be possible to fix this man page and perhaps put the source code of the demo program in the description instead of the name?

<img width="780" alt="Screenshot 2024-01-05 at 3 25 06 PM" src="https://github.com/PCRE2Project/pcre2/assets/33914892/f9c20e57-1bf3-42f3-9e2b-1c8554036312">
<img width="776" alt="Screenshot 2024-01-05 at 3 25 17 PM" src="https://github.com/PCRE2Project/pcre2/assets/33914892/7e473152-58c4-4e6c-bc25-d4a524c0c341">

**Comment by PhilipHazel** [comment]
Oops, yes, you are right. I have updated the page to put the source code under a section called SOURCE CODE, which seems a better title than DESCRIPTION. This is now committed in HEAD. I hope it solves your issue.
