### ISSUE TITLE
New release/roadmap

### ISSUE THREAD

**Issue by XVilka** [PCRE2Project/pcre2#373]
I apologize, but since no GitHub Discussions are enabled, opened an issue.

I see the last release was quite a long ago, and some notable changes have been made since. Are there any plans to make a new release soon?

**Comment by PhilipHazel** [comment]
A Release Candidate 10.43-RC1 was put out a couple of weeks ago. I am waiting a month to see if anybody actually tests it.

**Comment by carenas** [comment]
> since no GitHub Discussions are enabled

as described in the README (which is parsed in the GitHub page), the developers prefer to have all discussions done through a mailing list instead.

**Comment by PhilipHazel** [comment]
10.43 is out, so I am closing this issue.
