### ISSUE TITLE
Website problem: http to https redirections do not configurated

### ISSUE THREAD

**Issue by Neustradamus** [PCRE2Project/pcre2#385]
Dear @PCRE2Project, @PhilipHazel, @NWilson,

Can you change the server conf, to have a redirection from http links to https?

http://pcre.org/*
http://www.pcre.org/*
https://www.pcre.org/*
-> must be redirected to
https://pcre.org/*

Thanks in advance.

**Comment by addisoncrump** [comment]
No need to ping folks individually. The website issues are well-known, but just haven't been addressed yet. Maybe condense all these issues into one?

**Comment by PhilipHazel** [comment]
We are aware that pcre.org is out of date but the webmaster is not responding to messages.
