### ISSUE TITLE
pcre2 makes software crash when GDS mitigation is forced for older CPUs

### ISSUE THREAD

**Issue by bugreporter234** [PCRE2Project/pcre2#399]
When the Gather Data Sampling mitigation is forced on Linux for older CPUs (i.e. skylake), AVX instructions are disabled because there is no microcode update available.

lscpu:

```
…
Vulnerabilities:          
Gather data sampling:   Mitigation; AVX disabled, no microcode
…
```

This leads to software crashes when pcre2jit is enabled. For example qpwgraph crashes when a file dialog is opened and a pcre2jit function is called.

Backtrace:
[qpwgraph_gdb_backtrace.txt](https://github.com/PCRE2Project/pcre2/files/14649713/qpwgraph_gdb_backtrace.txt)

Keepassxc (password manager) doesn't start and reports 'illegal hardware instruction'. If pcre2 is compiled without jit it starts normally. Same for carla (audio rack/patchbay software).

**Comment by zherczeg** [comment]
AVX2 is not used unless CPUID says they are available.

**Comment by bugreporter234** [comment]
Well, normally AVX is available for skylake, but when the GDS mitigation is forced, it's not. So this is kind of a special case - a skylake CPU without AVX instructions. Do you think this special case can be handled somehow?

**Comment by zherczeg** [comment]
What cpuid says on that system?

https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitNativeX86_common.c#L512

Are these bits set? If cpu says it supports AVX, the software believes it.

We could add a compile time option to disable it, but you need to pass it manually.

**Comment by bugreporter234** [comment]
cpuid_tool (from libcpuid) says avx and avx2 are available, but `lscpu | grep avx` produces no output. So cpuid is wrong in this case.

[cpuid_tool_report.txt](https://github.com/PCRE2Project/pcre2/files/14668999/cpuid_tool_report.txt)
[lscpu.txt](https://github.com/PCRE2Project/pcre2/files/14669012/lscpu.txt)

A compile time flag would work for me, but I don't think it's a good solution, because not everybody with an affected CPU wants to recompile pcre2 and if Linux distros deliver pcre2 with jit enabled, the software would still crash for them.

**Comment by zherczeg** [comment]
What is a fairly easy and good solution then? It is surprising the cpu lies about the feature.

**Comment by loqs** [comment]
> It is surprising the cpu lies about the feature.

In addition to the CPU reporting it supports AVX support the OS must also support it. You can check for the support by querying bit 1 and 2 of the XCR0 register using the xgetbv instruction as documented in the Intel® 64 and IA-32 Architectures Software Developer’s Manual.

**Comment by zherczeg** [comment]
This is something new for me, although simple enough to use it. How can I test if this instruction is available?

Is there a description about its feature bits? I only found this:
https://en.wikipedia.org/wiki/Control_register#XCR0_and_XSS

This documentation tells that xgetbv has a non-deterministic behaviour:
https://google.github.io/security-research/pocs/cpus/xgetbv/

**Comment by loqs** [comment]
See the [Intel SDM](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html) Volume 1 Chapter 13 Managing State Using The XSAVE Feature Set (includes XGETBV and XCR0) and 
Volume 1 Chapter 14.3 Dectection OF Intel® AVX Instructions.

**Comment by zherczeg** [comment]
I have no time to read this much info. I only need the following info:
- How can I detect if the instruction is available?
- Is it supported by non-intel x86 cpus?
- The bitlist of XCR0 (I have already found it)

**Comment by loqs** [comment]
>     * How can I detect if the instruction is available?

CPUID.(EAX=01H, ECX=0H):ECX[bit 27] indicates OSXSAVE support it also indirectly implies the processor supports XSAVE, XRSTOR, XGETBV, and XCR0.

> 
>     * Is it supported by non-intel x86 cpus?
> 

Yes as the interface is standardized.

**Comment by bugreporter234** [comment]
> Edit: See example code in: https://www.intel.com/content/dam/develop/external/us/en/documents/how-to-detect-new-instruction-support-in-the-4th-generation-intel-core-processor-family.pdf
> 

I tried out the example code, removing all the features in line 8, leaving only `_FEATURE_AVX2` and it outputs:

`This CPU does not support all ISA extensions introduced in Haswell`

So this should work.

**Comment by zherczeg** [comment]
Ok I will do this in the sljit project in due course. It will be transferred into pcre2 before the next release.

**Comment by bugreporter234** [comment]
I applied logs' patch to 10.43 and it compiled successfully, but when I run `make -j1 check` the checks still fail with 'illegal instruction'. I'm compiling like Arch Linux does in the 10.43 [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/pcre2/-/blob/main/PKGBUILD?ref_type=heads).

[test-suite.log](https://github.com/PCRE2Project/pcre2/files/14695203/test-suite.log)

**Comment by bugreporter234** [comment]
I made a pcre2 package for Arch Linux with the patch applied (commenting out the checks) and installed it and now qpwgraph is crashing from the start. Without the patch it was crashing when I clicked 'Open' or 'Save as' (before a file dialog is opened). I also recompiled qpwgraph, just to be sure. Here's the backtrace of qpwgraph with the patch applied to pcre2:

[qpwgraph_gdb_backtrace_patch_applied.txt](https://github.com/PCRE2Project/pcre2/files/14695691/qpwgraph_gdb_backtrace_patch_applied.txt)

**Comment by zherczeg** [comment]
It looks like it is not in the jit-ed code, but during compilation: pcre2_compile_16. Could you disassemble the instructions around it:
`disassemble $pc-32,$pc+32`

Maybe it is the XGETBV instruction.

**Comment by bugreporter234** [comment]
```
Thread 1 "qpwgraph" received signal SIGILL, Illegal instruction.
0x00007ffff4d8dfb0 in pcre2_compile_16 (pattern=0x5555558bac60, patlen=<optimized out>, options=524288, errorptr=0x55555588c2e0, erroroffset=0x7fffffffd988, 
    ccontext=0x7ffff4e11c00 <_pcre2_default_compile_context_16>) at src/pcre2_compile.c:10267
10267	cb.start_pattern = pattern;
(gdb) disassemble $pc-32,$pc+32
Dump of assembler code from 0x7ffff4d8df90 to 0x7ffff4d8dfd0:
   0x00007ffff4d8df90 <pcre2_compile_16+304>:	xor    %cl,(%rdi)
   0x00007ffff4d8df92 <pcre2_compile_16+306>:	(bad)
   0x00007ffff4d8df93 <pcre2_compile_16+307>:	xor    $0x4a000005,%eax
   0x00007ffff4d8df98 <pcre2_compile_16+312>:	lea    (%rbx,%rsi,2),%edx
   0x00007ffff4d8df9b <pcre2_compile_16+315>:	mov    %rdx,-0x4688(%rbp)
   0x00007ffff4d8dfa2 <pcre2_compile_16+322>:	mov    -0x4690(%rbp),%rsi
   0x00007ffff4d8dfa9 <pcre2_compile_16+329>:	lea    0x5c190(%rip),%rdx        # 0x7ffff4dea140 <_pcre2_default_tables_16>
=> 0x00007ffff4d8dfb0 <pcre2_compile_16+336>:	vmovq  %rbx,%xmm3
   0x00007ffff4d8dfb5 <pcre2_compile_16+341>:	mov    -0x46a0(%rbp),%edi
   0x00007ffff4d8dfbb <pcre2_compile_16+347>:	movq   $0x0,-0x44e8(%rbp)
   0x00007ffff4d8dfc6 <pcre2_compile_16+358>:	mov    0x28(%rsi),%rcx
   0x00007ffff4d8dfca <pcre2_compile_16+362>:	vmovq  %rsi,%xmm2
   0x00007ffff4d8dfcf <pcre2_compile_16+367>:	mov    %edi,-0x44cc(%rbp)
End of assembler dump.
```

**Comment by bugreporter234** [comment]
> The following diff might be closer to your use case https://gitlab.gnome.org/GNOME/babl/-/issues/96#note_2056377

I tested this babl patch and it fixes the babl and gimp crash, which is unrelated to pcre2, but the logic there seems to solve the problem.

**Comment by zherczeg** [comment]
the name `vmovq`  is a VEX prefixed version of `movq`, so your compiler automatically generates AVX2 instructions. You need to set the instruction set (or the cpu type) before compiling.

**Comment by zherczeg** [comment]
Added to sljit https://github.com/zherczeg/sljit/commit/56dbde07b05252f0b304b04040a86cfb9f109ae9

**Comment by bugreporter234** [comment]
Looks good! No more crashes. Tested sljit first and without the new patch I get 'illegal instruction' from the `./bin/sljit_test`; with the new patch applied I get a PASS. And I made a pcre2 package for Arch Linux with the new patch and it fixes all the crashes. Thanks a lot!

**Comment by PhilipHazel** [comment]
There has clearly been a Happy Ending, so I am closing this issue.
