### ISSUE TITLE
I use pcre2 to do text postprocessing, and encountered a core problem.

### ISSUE THREAD

**Issue by housebaby** [PCRE2Project/pcre2#40]
Can anyone git me a hint about this problem 
No idea how to fix  it 
![image](https://user-images.githubusercontent.com/9246556/140895981-26dc8393-53e4-4161-a1f4-0bc5829941fd.png)

**Comment by zherczeg** [comment]
Could you share a pattern and some minimal input where the issue can be reproduced?

**Comment by PhilipHazel** [comment]
I am closing this because no more information has been provided.
