### ISSUE TITLE
Invalid size 0 may lead to undefined behavior / infinite loop 

### ISSUE THREAD

**Issue by jvanegue** [PCRE2Project/pcre2#400]
Function pcre2_substring_nametable_scan is externally exposed contains ill-defined case where size = 0 leading to undefined behavior / infinite loop 

PR submitted (2 lines changes) - See https://github.com/PCRE2Project/pcre2/pull/398 for details

Thank you,
Julien Vanegue

**Comment by PhilipHazel** [comment]
See my comment on the PR.
