### ISSUE TITLE
Atomic group must not increase stack depth

### ISSUE THREAD

**Issue by mvorisek** [PCRE2Project/pcre2#401]
Currently, when `(?:` (non-capturing group) is changes to `(?>` (atomic group), it increases stack usage causing JIT matching to fail with the following error:

```
JIT stack limit exhausted
```

This is problematic in deeply recursive regexes as it seems atomic group adds at least +1 stack depth per recursion.

I would expect this to be handled stackless.

Here is an example where we had to reduce atomic group usage to workaround this issue: https://github.com/mvorisek/PHP-CS-Fixer/commit/fbce0f46672ffd2ba11586e1a84a517a55ae2fd3

**Comment by zherczeg** [comment]
Depends on the pattern. Assertions and atomic blocks needs to be reverted when they fail. E.g: `(?>(a))b` this adds a capturing bracket, which needs to be reverted if `b` fails to match. Marks, start of match, etc. needs to be reverted as well. So entering to an atomic block / atomic assertion may trigger many variable savings. I remember the engine optimizes some simple cases, but this has limitations.
