### ISSUE TITLE
Probable thread-safety issue in pcre2 10.43+

### ISSUE THREAD

**Issue by lbonn** [PCRE2Project/pcre2#402]
Our application is matching elements against patterns in several concurrent threads and we had some crash reports from users who updated to recent pcre2: https://github.com/davatorium/rofi/issues/1966.

After a collective effort, we tracked down a probable culprit as a regression introduced in https://github.com/PCRE2Project/pcre2/commit/d84f255bef4d956d67ff5da35024e7a8c0c7e669, in particular the locking logic in the jit allocator.

From an educated guess, the fix could be to protect (again) some fields access in next_header, as these are also read in the free() function:

```
diff --git a/src/sljit/allocator_src/sljitExecAllocatorCore.c b/src/sljit/allocator_src/sljitExecAllocatorCore.c
index 85f3a9d..2fc91c2 100644
--- a/src/sljit/allocator_src/sljitExecAllocatorCore.c
+++ b/src/sljit/allocator_src/sljitExecAllocatorCore.c
@@ -237,12 +237,12 @@ SLJIT_API_FUNC_ATTRIBUTE void* sljit_malloc_exec(sljit_uw size)
                header->size = chunk_size;
                next_header = AS_BLOCK_HEADER(header, chunk_size);
        }
-       SLJIT_ALLOCATOR_UNLOCK();
        next_header->size = 1;
        next_header->prev_size = chunk_size;
 #ifdef SLJIT_HAS_EXECUTABLE_OFFSET
        next_header->executable_offset = executable_offset;
 #endif /* SLJIT_HAS_EXECUTABLE_OFFSET */
+       SLJIT_ALLOCATOR_UNLOCK();
        return MEM_START(header);
 }
```

It stopped crashing after this change for at least one of the testers.

CC: @christian-heusel, @DaveDavenport, @ravomavain, @dennisschagt

**Comment by zherczeg** [comment]
Just the other day I was also wondering why the unlock mas moved before the end of the function. It just felt wrong. @carenas do you remember?

https://github.com/zherczeg/sljit/commit/7de0fee9a7376b33e31a3903487cd9933da3a606#diff-249fa9ceb0eb2b074dbaa38dfca020158e15e36e8a7b5d0aca1443226bf4b63aR243

**Comment by carenas** [comment]
> It just felt wrong. @carenas do you remember?

It was likely unintentional and therefore a bug

**Comment by easyteacher** [comment]
https://bugs.kde.org/show_bug.cgi?id=484514 has a similar backtrace

**Comment by lbonn** [comment]
@zherczeg @carenas should I open a PR to sljit and pcre2 with this small change or do you prefer to handle it yourself?

A fair number of users seem affected and the bug might have security implications as it causes memory corruption.

**Comment by zherczeg** [comment]
Up to you. Let me know your decision.

**Comment by lbonn** [comment]
@zherczeg thanks for the very quick merge :)

**Comment by lbonn** [comment]
Fix is now in the master branch https://github.com/PCRE2Project/pcre2/commit/e466d418a938d5575da4109b0d5bf1cb37119ab3, thank you!

**Comment by dangelog** [comment]
Hi! Do you think this warrants a release, given the bug causes crashes?

**Comment by PhilipHazel** [comment]
Probably fairly soon, but I am currently chasing down an obscure bug that oss-fuzz found and it would be nice to have that cleared up as well.
