### ISSUE TITLE
Long-term maintenance of PCRE2

### ISSUE THREAD

**Issue by PhilipHazel** [PCRE2Project/pcre2#426]
I am posting this message on pcre2-dev@googlegroups.com and also as an issue on the PCRE2Project on GitHub so that it gets to as many people as possible.

I implemented PCRE in the summer of 1997, never expecting it to be still going strong 27 years later, nor be as widely used as it seems to be. Except for the JIT code that is Zoltan's, the development and maintenance of PCRE has been my own project, though of course many others have offered patches and suggestions over the years.

The time has come to think about my successor. I have recently had a Big Scary Birthday and am unfortunately beginning to feel my age. It would be a good thing if the PCRE2 project could be passed on to others while I am still around to help with the transition.

If anybody has any suggestions as to how best to go about this, please get in touch.

**Comment by conartist6** [comment]
<img width="449" alt="Screenshot 2024-06-12 at 7 09 54 AM" src="https://github.com/PCRE2Project/pcre2/assets/540777/55999229-4e69-435a-b292-933f70c6bd96">

Thanks for everything you've put into it!

**Comment by addisoncrump** [comment]
I'll happily contribute to testing code where I am able, esp. automated testing. @carenas has been associated with the project for some time and of course @zherczeg develops the JIT.

Any maintainer who answers this call would have support in these regards.

**Comment by alexdowad** [comment]
@PhilipHazel Thanks very much for providing this fine tool to the world and maintaining it for all these years.

Maintaining PCRE2 sounds fascinating, but a bit intimidating. How do you ensure that each new release works on all supported platforms? For example, I see in the source tree that there is a port to OpenVMS. Do you have a test machine running OpenVMS?

**Comment by PhilipHazel** [comment]
The short answer is that I cannot test everything. The OpenVMS stuff comes
from a contributor who sends updates from time to time. Likewise the Zig
and Bazel support files. All I have is a 64-bit Arch Linux system - I can
no longer test on a 32-bit machine - hence the recent SNAFU with the tests
on 32-bits. GitHub actions are used to run automated tests in some other
environments and the builds for the oss-fuzz tests sometimes pick up
issues. I used to put out a Release Candidate for each release but found
that not many people tested them. On the whole, if PCRE" builds, it will
work because the main library is pure C code.

I have had a couple of other people express interest in taking on the
maintenance; I'm leaving it a few more days before proceeding. Would you
like to be involved in the discussions?

**Comment by MatthewVernon** [comment]
I'd just like to say thank you for all your work on pcre (and, indeed, Exim)! 
As the current Debian maintainer for PCRE, I'd be interested in discussions about PCRE's future, although I think I am not the right person to be "upstream" as Debian puts it.

**Comment by alexdowad** [comment]
> Would you like to be involved in the discussions?

Dear @PhilipHazel, certainly, I am interested. :smile: My privmail address is in my GitHub profile.

**Comment by PhilipHazel** [comment]
@MatthewVernon , please can you let me have an email address to add to my (private) list of interested parties. I'm planning to start a discussion by email in a few days' time.

**Comment by MatthewVernon** [comment]
@PhilipHazel sure - best to use matthew at debian dot org

**Comment by Neustradamus** [comment]
@PhilipHazel: Good job since this long time and for @Exim project too.

**Comment by Neustradamus** [comment]
@PhilipHazel: Good job since this long time and for @Exim project too.

Do not forget to add the new team here:
- https://sourceforge.net/projects/pcre/

And to send access to the website...

Linked to:
- https://github.com/PCRE2Project/pcre2/issues/154
- https://github.com/PCRE2Project/pcre2/issues/385
- https://github.com/PCRE2Project/pcre2/issues/386
- https://github.com/PCRE2Project/pcre2/issues/387

**Comment by PhilipHazel** [comment]
I am not responsible for the sourceforge site, nor pcre.org. The webmaster has not been responding for quite a long time now.

**Comment by ljavorsk** [comment]
Hi Philip, sorry for the late reply, I assume the conversation with the interested parties has already begun (or maybe already finished).

Would it be possible to add me to the thread, so I (as the maintainer of pcre2 for Fedora/RHEL/CentOS Stream) can have the information about the future steps and plans of this project?

My email address is in my GitHub profile.

Thank you so much again for all the work you've put into this ❤️

**Comment by PhilipHazel** [comment]
Hi Lukas, the conversation with interested parties has very much died down, but there's been a flurry of work happening in PCRE2 as you will see if you look at the Git log and/or GitHub issues and pull requests. Just in case another email conversation happens, I have added you to my list of interested parties, but there are no active email threads at the moment.

**Comment by zherczeg** [comment]
As far as I know there is no sponsored maintenance behind pcre2, and it does not seem to change. We do what we can in our free time, but there are other priorities (job, family) in our life, so there is no guarantee when we respond to a problem. There are times, when we are quite active, and there are times when we are kind of non-existent. But it is unlikely we abandon the project since we have already spent a lot of effort on it. This also means there are no fixed plans for the future. People focus on areas they like.

**Comment by shenlebantongying** [comment]
Maybe this issue should be pinned so that anyone visiting the issue will see it. “Pin issue” button is on the right sidebar.

https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository

**Comment by PhilipHazel** [comment]
Good idea. Pinned.

**Comment by NWilson** [comment]
I would cautiously be interested. PCRE2 is quite a precious piece of code, and I wouldn't trash it. (Nor am I malicious - I can happily meet in person for a beer!) My only worry is whether I'd really have time in future.

Helping out on two releases doesn't seem _too_ onerous. Reviewing code during busy periods could become a little burdensome.

In general, the codebase is in a healthy state, with good documentation. I feel Philip could leave it, and we'd be able to work everything out without needing to ask questions. It takes a few hours extra to get inside someone else's thoughts, but I'm used to doing that with some old codebases I work on.

**Comment by PhilipHazel** [comment]
Nick, thank you for your interest. Until this recent flurry of issues and PRs, things had been very quiet for PCRE2, which is why I thought it was a good time to raise the issue of who could take over from me. The recent activity has been very reassuring that there are now a number of people who have detailed knowledge of the code and are interested in its future. Once we get 10.45 released, I think things could well quieten down again (maybe :-)  so management may not need too much time.  

The one thing that only I have ever done is to make a new release. There are some notes on this in maint/README and in fact I have a private shell script that automates the process. The Arch Linux packager, @dvzrv  raised issue #417 about the signing of Git objects. I have not been signing the release tags (because I didn't know you could) but of course that could be done. I do sign the release tarballs and zipball and @dvzrv  was concerned that there should be a proper handover to any new signer. I'm only a very limited GPG user, but no doubt there are protocols for this kind of thing. I suspect meeting in person might be part of this.

I'm happy to meet for a beer, but more likely coffee because I don't go out much in the evenings these days.

**Comment by NWilson** [comment]
For coffee, of course! I'd be happy to take on some GPG signing, that's really not a big task, given it only needs to done occasionally.

For the 10.45 release, let's make sure that all the private steps are written down, and we all know what's involved (although the notes in `maint/` seem quite thorough already).

**Comment by MatthewVernon** [comment]
Likewise, my GPG key is reasonably well-distributed already, thanks to Debian ;-)

**Comment by PhilipHazel** [comment]
I am closing this issue, because @NWilson has now taken over as principle maintainer of PCRE2.

**Comment by Neustradamus** [comment]
Thanks again @PhilipHazel for all your work, I will continue to find a solution for pcre Sourceforge project (@andrewgho) and domain name. The new team needs to recover.

**Comment by Neustradamus** [comment]
Thanks again @PhilipHazel for all your work, I will continue to find a solution for pcre Sourceforge project (@andrewgho) and domain name. The new team needs to recover.

And welcome to @NWilson :)
