### ISSUE TITLE
Case-insensitive \p{} issue

### ISSUE THREAD

**Issue by michaeltang4829** [PCRE2Project/pcre2#432]
Hello,

We're using PCRE2 10.43, and we found what looks to be a bug with unicode properties while using character case properties. When the pattern has the case-insensitive modifier, regardless of the character case being only upper-case, should also find lower case characters. 

Text: `a`
Pattern: `(?i:\p{Lu})`
Result: No matches
Expected: `a`

There's also documentation in section 17 in the [pcre2compat](https://pcre2project.github.io/pcre2/doc/html/pcre2compat.html) page hinting that this was the original behavior in Perl, but later Perl corrected this behavior. 

Thanks!

**Comment by PhilipHazel** [comment]
Commit 6d82f0c makes PCRE2 behave like Perl. Lu, Ll, and Lt now all behave as Lc when /i is in force.
