### ISSUE TITLE
PCRE2 deviates from unicode special case

### ISSUE THREAD

**Issue by michaeltang4829** [PCRE2Project/pcre2#434]
Hello,

We are using PCRE2 10.43. 

We have noticed that PCRE2 isn't following the unicode special casing standard. This primarily affects languages such as Greek, Turkish, Lithuanian, Latin, and miscellaneous ligatures when using case modifiers during substitutions. 

**Example:**
Text: `ΘΣ`
Pattern: `\w+`
Replacement: `\L$0`

Current Result: `θσ`
Expected Result: `θς`

**Explanation**: 
The Unicode standard provides details on case mapping [here](https://www.unicode.org/faq/casemap_charprop.html). The majority of unicode characters have a one-to-one case mapping and are locale and context independent defined in [UnicodeData.txt](https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt). For special casing rules, there is [SpecialCasting.txt](https://www.unicode.org/Public/UCD/latest/ucd/SpecialCasing.txt). In the example above, the last character in the text is the Greek Sigma `Σ` (0x03A3). The special casing rule indicates that if that character is the last letter of the word, the lower casing mapping should lead to Lower Sigma `ς` (0x03C2). 

```
# Special case for final form of sigma
# <code>; <lower case>; <title case>; <upper case>; (<condition_list>;)? # <comment>
    03A3;         03C2;         03A3;         03A3;       Final_Sigma;   # GREEK CAPITAL LETTER SIGMA
```

However, PCRE2 is only following the one-to-one mapping in this case and is returning `σ` (0x03C3). 

The example is just one rule in SpecialCasting.txt. Though I did not test the other rules in the file, it may be likely that PCRE2 does not follow any of the special casing rules.

**Comment by PhilipHazel** [comment]
You are right. PCRE2 does not support any of the special casing rules. I have made a note to add this information to the documentation.

**Comment by PhilipHazel** [comment]
I have updated the documentation in HEAD. A quick test suggests that Perl doesn't support the special casing rules either, though maybe there is an option.
