### ISSUE TITLE
pound reverse proxy compiled with pcre2 segfaults

### ISSUE THREAD

**Issue by johndoe7000** [PCRE2Project/pcre2#438]
Hello devs,

I would like to inform you, that libcre2 (or, at least prce2posix) is not thread-safe.

Please look here...
https://github.com/graygnuorg/pound/issues/33

Regards,
Darius

**Comment by carenas** [comment]
> I would like to inform you, that libpcre2 (or, at least prce2posix) is not thread-safe

pcre2posix is [documented](https://pcre2project.github.io/pcre2/doc/html/pcre2posix.html) as not being thread safe

**Comment by johndoe7000** [comment]
Ohhhh, OK... didn't read that... sorry for the noise... closing.
