### ISSUE TITLE
Release request: v10 45

### ISSUE THREAD

**Issue by Ayesh** [PCRE2Project/pcre2#467]
This is merely a request to see if we can cut a 10.45 release? 

PHP includes PCRE2 in it's source, and although it is possible to compile PHP with a patched PCRE2 source, it would be nice to have PCRE2 10.45 in the PHP source before it hits the PHP 8.4 feature-freeze.

If there are any release blockers, please completely disregard this. Otherwise, I would like to kindly request and see if we can cut the 10.45 release. 

Thank you.

**Comment by PhilipHazel** [comment]
There's a new optimization nearing completion which it would be nice to get into the next release - but that is, IMHO, sufficiently novel that we will probably put out a Release Candidate for a month or two. Also, 10.44 came out in June, and we usually leave around 6 months between releases, though that is a minor point. A third delaying factor is that I want to hand over release building to someone else, and that will need organizing. Bottom Line: unfortunately, there seems to be a timing mismatch with PHP.

**Comment by Ayesh** [comment]
Understood! I'd pick these optimizations and Alex being a potential maintainer over a minor release too! Thank you.
