### ISSUE TITLE
The xclass caseless repetition problem

### ISSUE THREAD

**Issue by zherczeg** [PCRE2Project/pcre2#469]
Would be great to do something with caseless repetitions in xclass. Example:
```
  re> /[\pC\x{17b}\x{17c}]/i,utf,fullbincode
------------------------------------------------------------------
  0  21 Bra
  3     [\p{C}\x{17b}-\x{17c}\x{17b}-\x{17c}]
 21  21 Ket
 24     End
------------------------------------------------------------------
```

The question is where. During compilation, in the META phase, the buffer might be too small to have the proper ranges. In the byte code generation phase, computing it twice would be costly. Can we reallocate the buffer in the META phase, and do all caseless checks there? Maybe do all checks there, including the class to single character optimization.

**Comment by carenas** [comment]
Assume that by "META phase" you refer to `parse_regex()`?, eitherway, now that we are introducing a "rewrite phase" soon after that and that needs to reallocate the parsed regex anyway, might make sense to do it there.

**Comment by carenas** [comment]
Also curious, where is this duplication problematic, and if is it worth doing any optimization to prevent it (specially if after compilation?), for example wouldn't the following also be technically more "efficient" by rewriting? (ex: `[\p{Cn}\pC] => \pC`)

**Comment by PhilipHazel** [comment]
I expect Zoltan is thinking that duplication is wasted effort at match time. All the handling of case-independence is done at compile time so that the match phase doesn't have to keep track of where and where not it applies. (An earlier PCRE did, but pulling it out to compile time simplified things and must have benefited performance.) Because wide characters (and ranges) and just listed in an XCLASS, the compiler adds the other case to the list, but as has been pointed out, there is no duplication checking. 

Your suggestion above of a different kind of optimization is also legitimate. However, how far should we go in such things? Who is actually going to write [\p{Cn}\pC]  ?  If we are thinking of programs generating patterns, then it really should be the generating program that does its own optimization, IMHO.

**Comment by zherczeg** [comment]
I would like to optimize actual ranges only, no properties. The ranges should be sorted, so we can use logarithmic search, which is much faster for many ranges.

**Comment by zherczeg** [comment]
Since the character sizes are not fixed in utf, the whole binary search should be implemented as byte code. Structure could be something like this:

Range list start with a pointer to `end`: LINK_SIZE

Operation types:
LESS_THAN: followed by a `c` character. If the current character is less than `c`, we have a match, and code pointer goes to `end`. A `c` set to 0 never matches because of less than.
GREATER_OR_EQUAL_THAN: followed by `c` and a pointer LINK_SIZE. If the current character is >= 'c', 'c' subtracted from the character, and code pointer is moved ahead by LINK_SIZE.

Since we have only two operations, perhaps we could encode them without an operation byte in some way.

Probably LESS_THAN, GREATER_OR_EQUAL_THAN are in pairs, and can be encoded as `c`, `c`, LINK_SIZE. This way we have only one type of operation. If the first `c` is 0, no GREATER_OR_EQUAL_THAN part, and match fails.

**Comment by zherczeg** [comment]
Btw the 0..MAX_UTF range cannot be encoded in the structure above, since MAX_UTF+1 cannot be encoded in UTF16. But this is the same as ALL characters. If we have at least one range, 'c' is always <= MAX_UTF. Maybe for a few ranges (<=2) we could simply use the current method.

**Comment by zherczeg** [comment]
There is progress on this, the issue can be closed.

**Comment by NWilson** [comment]
> The binary search searches the lower_bound of a search_value = ((original_character_value << 1) | 1) in the list.
The original_character_value is in the list, if search_value == lower_bound || (lower_bound & 0x1) == 0.

Genius! It's self-synchronising so you can bisect it, and recover whether you have a range or single character.

How important is it to use tricks like this to shave off bytes? It seems OK, but not super-necessary.

We can encode it like this:

```c
#define XCL_NOT      0x01  /* Flag: this is a negative class */
#define XCL_MAP      0x02  /* Flag: a 32-byte map is present */
#define XCL_HASPROP  0x04  /* Flag: property checks are present. */
#define XCL_HASNOTPROP  0x08  /* Flag: not property checks are present. */
#define XCL_HASRANGE_A 0x10  /* Flag: Zoltan's "range A". */
#define XCL_HASRANGE_D 0x80  /* Flag: Zoltan's "range D". */

get rid of XCL_END and the others...
```

| length | contents |
|---|---|
| 1 SPTR | OP_XCLASS |
| LINK_SIZE | length of the whole opcode |
| 1 SPTR | the XCL_ flags above |
| 32 bytes | _if_ the XCL_MAP set, then the map |
| ... | a length-prefixed list of props, _if_ the XCL_HASPROP is set |
| ... | a length-prefixed list of props, _if_ the XCL_HASNOTPROP is set |
| ... | a length-prefixed list of ranges, _if_ the XCL_HASRANGE_A is set |
| ... | ... |

The sections don't need any tags to indicate what they are, we just include them always in the same order, based on whether the flag indicates to include the section.
