### ISSUE TITLE
Make PCRE2_ASSERT work

### ISSUE THREAD

**Issue by zherczeg** [PCRE2Project/pcre2#484]
Even with `--enable-debug` this code does not work:

https://github.com/PCRE2Project/pcre2/blob/master/src/pcre2_util.h#L56

As far as I know, `__builtin_unreachable` has no effect, only informs the compiler. A failed assertion should stop execution. Is there a flag needed to be passed to the compiler?

Debugging should not involve complicated methods, the purpose is catching errors not high performance.

**Comment by zherczeg** [comment]
@carenas can you help me?

**Comment by carenas** [comment]
I couldn't see a problem with my compilers, but they are all fairly recent, which one did you have problems with?

**Comment by zherczeg** [comment]
gcc 11.4.0. What happens for unreachable in your system when an assert fails? The description of unreachable says what happens is random, since no code is generated, and the next code is simply executed. As for asserts, the compiler considers it as a dead code, since the assert has no side effect.

**Comment by zherczeg** [comment]
https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

"If control flow reaches the point of the __builtin_unreachable, the program is undefined." Nothing happens is a perfect effect.

**Comment by carenas** [comment]
> gcc 11.4.0. What happens for unreachable in your system when an assert fails?

the compiler introduces an `ud2` instruction that kills the program:

```
illegal hardware instruction  ./pcre2test
```

**Comment by zherczeg** [comment]
Do you need a compiler option for that? Maybe it is better to move back to more reliable methods, especially if undefined becomes defined in the future.

**Comment by carenas** [comment]
No additional compiler option needed, agree it will be better not to rely on "undefined behaviour" for this, but was waiting on @alexdowad input since this was originally his code.

Lets give him some time, specially considering you have a "workaround" as well AFAIK,

**Comment by alexdowad** [comment]
Ah, for MS Visual C++, there is also `__assume`, which might be more appropriate than `__debugbreak`.

**Comment by zherczeg** [comment]
This is debug only, so the most reliable is the best for me. I also prefer if some info is printed. What shall we do?

**Comment by carenas** [comment]
> What shall we do?

Just using assert() by default might be better IMHO, will prepare a PR

Note that assert() is part of ANSI C, so it shouldn't be much of a concern, portability wise, to do so.

**Comment by MatthewVernon** [comment]
I think I'd vote for just using the existing `assert`-based implementation; as @carenas observes, it's part of C99 and POSIX, so should be available basically everywhere (and we have the fallback based on `abort` available if there is a platform without it).

**Comment by zherczeg** [comment]
@alexdowad no problem. It is interesting to know that unreachable asserts when asan is enabled. Can be useful.
