### ISSUE TITLE
Consider removing $name from substitution syntax

### ISSUE THREAD

**Issue by NWilson** [PCRE2Project/pcre2#500]
The `$name` syntax in substitutions is not ideal.

* It's idiosyncratic to PCRE2. I can't find any other engine supporting it. Other engines such as Perl, .NET, and Java support `${name}` or `$+{name}` syntax, but not unbracketed names.
* It has some unfortunate Unicode implications, because there's no delimiter around the free text `name`. In the substitution `$nameX`, where `X` is some random Unicode character, the substitution parser is really strongly depending on the Unicode character properties of `X` to interpret the syntax. If X is a high code point, which a future version of Unicode decides to assign to a Letter, then it will break the parse.

  Is this a problem in practice? Almost certainly not. But it will cause our managers to pause in fear, over a simple update of the supported Unicode version, because we can't guarantee that the parser will be backwards-compatible.

  Note that the Unicode Consortium has a nice policy on backwards-compatibility: https://www.unicode.org/reports/tr31/

  They promise not to remove the "Letter" status from characters, but they certainly can add it to new characters in future.

  In general, it's just bad practice to have free text with unclear delimiters. In a language like C, or Perl, with statements like `my $var=...` the parser is scanning for `=` or whitespace after `$var`, so it's not sensitive to the Unicode character properties in the same way that `$nameX` is (where it is legal for X to be any user-chosen character).

We could: 
* Accept the way it is. (Genuine option)
* Add an EXTRA flag to control the behaviour... (urgh, not another one!)
* Simply remove it, on the basis that `pcre2_substitute()` is not as widely used as the rest of the API, and that in addition, named capture groups are used fairly infrequently. This is of course breaking.

**Comment by PhilipHazel** [comment]
Perl does support $name in substitution strings, though it's not what you think:

> $ cat zz
> $x = "X";
> $y = "123";
> $y =~ s/2/$x/;
> print "$y\n";
> 
> $ perl zz
> 1X3

I think that's probably why I originally implemented it that way. PCRE1 added named subpatterns, following Python, back in 2003, but the substitution function didn't arrive till the first release of PCRE2 in 2015. I cannot remember whether Perl had named subpatterns by then. Probably, but I obviously didn't look at its syntax for references in substitutions, which is $+{name}. 

I think I would be unhappy at potentially breaking things by just removing it, especially as I suspect that there are quite a lot of non-Unicode applications about. A deprecation warning could be added to the documentation, however, explaining where the potential problem is.

**Comment by NWilson** [comment]
Sorry I wasn't clear, yes, I meant "the `$name` syntax for referencing capture groups is idiosyncratic to PCRE2". That's not a criticism either, just an observation.

I guess a deprecation warning would be nice; I agree it's not worth breaking anyone's applications over this.

**Comment by carenas** [comment]
With the risk of stating the obvious, wanted to clarify that it is not only an Unicode issue; as Nick explained before, the lack of delimiters makes the syntax ambiguous, so for example:

```
  re> /(?:(?<x2>X)|(?<x>Z))/
data> Z\=replace=$x2
```

Probably should return an error if tried under a new `PCRE2_SUBJECT_STRICT_NAME` option in those (and the Unicode enabled names) cases?

**Comment by PhilipHazel** [comment]
Having thought about this some more: it has been the case forever that $name is available in Perl strings for variable interpolation. I think people are used to this, and know that you need to use ${name} when there is a possibility of ambiguity. If there is no such possibility, the braces just clutter up the string. So I'm not even sure we need a warning in the docs, though I would not object to it.

**Comment by NWilson** [comment]
OK, I'll close this.

Thank you for the discussion.
