### ISSUE TITLE
Clarification about scan_substring

### ISSUE THREAD

**Issue by NWilson** [PCRE2Project/pcre2#533]
In the ChangeLog file, the new scan substring feature is described as "experimental".

I believe that it wasn't in the July 10.44 release, so currently that code has had very little public exposure or use.

What exactly does "experimental" imply here? Would it be foolish for Excel to release this feature in our REGEX support, bearing in mind that any features released in Excel are basically locked-in for eternity?

Other new PCRE2-specific behaviours, like napla, seem to have stable and clear syntax and behaviour, so I don't see a problem to offering these older features.

**Comment by zherczeg** [comment]
It simply means, that before the next release, anything can be changed including syntax. However, after the next release, only backwards compatible changes are possible. So, if you have any suggestions, it is better to tell us before the next release. The feature is quite powerful, so I think people will like it. Anyway, it is your decision what to support in Excel.

**Comment by PhilipHazel** [comment]
I am expecting to have to spend time on reviewing all the docs when we are close to the next release, at which point the word "experimental" should get removed, I think. Most things released in PCRE2 are also locked in for eternity, or at least till PCRE3. :-)
The Wild West days of early PCRE1 releases are over; I've recently been looking at the start of the PCRE1 ChangeLog and been surprised at how much I have forgotten about those early releases (and a bit embarrassed at some of the oddities).

**Comment by carenas** [comment]
FWIW the `pcre2_convert` set of APIs are still experimental and were released in 2018, but as everyone said before, and you had noticed with your suggestions to break backward compatibility that hadn't been successful most things are locked once they are released (not including snapshots or RCs)

**Comment by PhilipHazel** [comment]
Yes, perhaps it's time to remove "experimental" from the convert functions. Good point.

**Comment by carenas** [comment]
BTW, not only "user" visible changes get locked, but also "developer" interfaces, so in that line I am still concerned about the new callback for substitution that still has IMHO no clear path to eventually supporting non 1 to 1 mappings.

**Comment by NWilson** [comment]
I've opened Carlo's feedback here: #564

I agree that once they've been released, PCRE2 APIs can't change without an extremely, extremely good reason.

**Comment by zherczeg** [comment]
Usually we add new API to "replace" old API. Or add more flags. We did it a lot in PCRE1. Then Philip just rewrote the whole API and introduced PCRE2.

**Comment by carenas** [comment]
PCRE2 is also extremely at risk of ABI breakage becuse we don't even have versioned symbols as raised in [Debian bug 902060](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902060).

If we decide to go with the "experimental" interface might become a blocker for release.
