### ISSUE TITLE
(Maybe) remove handling of quantifiers after OP_FAIL

### ISSUE THREAD

**Issue by NWilson** [PCRE2Project/pcre2#541]
I am leaving a TODO in pcre2_compile.c

In the PR #511 Zoltan changed the parser so it doesn't emit OP_FAIL anymore for empty character classes. Hence (according to the comments at least) it should no longer be possible for an OP_FAIL to have a following quantifier. The code to handle this could be removed.

Or, if I'm wrong, then the TODO can be removed, and the comments updated to explain why OP_FAIL can have a quantifier after.

**Comment by zherczeg** [comment]
We might need to emit empty xclasses inside eclasses, which could also handle the nothing match cases. This could save some space.

**Comment by NWilson** [comment]
The line of code that needs changing is tagged with this URL:

`https://github.com/PCRE2Project/pcre2/issues/541`

I won't be brave and make the change myself, because I don't understand OP_FAIL well enough. There's just a tiny loose end for someone else (hopefully) to tie up.
