### ISSUE TITLE
Add lcov coverage report to CI jobs

### ISSUE THREAD

**Issue by NWilson** [PCRE2Project/pcre2#555]
There are various error cases and stray blocks of code that appear not to be covered by the unit tests.

We should do a little bit more monitoring of the `lcov` report, and close any loopholes.

Noticed while checking for missed lines or branches in the new extended classes code.

**Comment by PhilipHazel** [comment]
In the past I have had several "coverage blitzes" where I have taken time to add tests to improve coverage, and also add some LCOV comments to exclude code which can never partake in tests. However, the last time I did this was quite a while ago. You are right that it is time to do this again. Perhaps when all the current work in progress is complete?

**Comment by NWilson** [comment]
I can tell you've worked hard on the coverage, because overall it's excellent. No-one ever gets above 80% coverage unless they're seriously committed to exhaustive testing.

Yes, let's hoover up the coverage gaps once things have quietened down.

This doesn't block a 10.45 RC, but could be done during that time.

**Comment by NWilson** [comment]
We can also add Clang's scan-build (clang-tidy) static analysis. I know we already have Coverity, but that's a bit of a black box. I find Clang's scanner very good, and it _can_ find bugs, from time to time.
