### ISSUE TITLE
pcre2 misdetects __builtin___clear_cache() on some platforms with LLVM

### ISSUE THREAD

**Issue by pkubaj** [PCRE2Project/pcre2#92]
In https://github.com/PhilipHazel/pcre2/blob/master/src/sljit/sljitConfigInternal.h#L322, pcre2 checks for existence of __builtin___clear_cache() function. LLVM provides that function for all platforms, even those that don't have implemented flushing the cache: https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/builtins/clear_cache.c#L61

This leads to runtime errors on e.g. powerpc (32-bit) with __clear_cache() calling compilerrt_abort(), resulting in SIGABRT.

**Comment by zherczeg** [comment]
Summon @carenas

**Comment by carenas** [comment]
> This leads to runtime errors on e.g. powerpc (32-bit) with __clear_cache() calling compilerrt_abort(), resulting in SIGABRT

could you provide more details about the system and compiler version where this is still triggered?, FWIW debian bookworm / ppc64 with clang 8 (the oldest available, but all versions would do) doesn't seem to trigger it (using the upstream sljit to test, which includes required fixes for gcc) : 

 ```
$ git clone https://github.com/zherczeg/sljit.git
$ cd sljit && make CC='clang-8 -m32'
$ bin/sljit_test -s
SLJIT tests: all tests are PASSED on PowerPC 32bit (big endian + unaligned) (with fpu)
```

**Comment by pkubaj** [comment]
It's FreeBSD 13.1-BETA3 with LLVM 13.0.0. For me also all the tests pass, but it looks like the tests don't test SLJIT_CACHE_FLUSH.

**Comment by carenas** [comment]
SLJIT_CACHE_FLUSH is tested implicly by sljit tests 11 and 12, as they need to clear the cache after the code self modifies.

did you get the failure with a specific pcre2 version, the sljit code I pointed at is still not integrated into pcre2's HEAD and has a couple of fixes that corrected similar issues with gcc in sparc and power (the builtin is not implemented at all so those tests would fail as the cache was never cleared, IMHO clang's plan with their "abort" was to get reports of this builtin use so it will be implemented where needed AFAIK)

**Comment by pkubaj** [comment]
Here https://github.com/zherczeg/sljit/blob/master/sljit_src/sljitConfigInternal.h#L327 you clearly set that this code is not compiled when using clang. This explains why it works correctly. Indeed this check is missing from pcre2.

I have the last 10.39 version of pcre2.

**Comment by carenas** [comment]
@zherczeg: this is addressed already by the latest code in sljit and therefore could be provided as a patch for next pcre2 release.

@pkubaj: this is still worth reporting to LLVM so the clang implementation for this builtin is fixed there so it doesn't abort in 32-bit power (which affects at least two platforms for FreeBSD), pcre2/sljit have fallback code that can be used when the builtin is unreliable, but other users might not.

**Comment by pkubaj** [comment]
I fix packages for ppc* on FreeBSD so I will know rather quickly what doesn't build. The issue here is quite easy to spot during building - compiled binaries fail with SIGABRT.
Obviously, they may compile successfully (like php) and just abort during building a reverse dependency (like php), but anyway, I'll probably pick up 99% of the packages affected.
BTW, pcre is also affected. Could there be a release for the legacy pcre as well?

**Comment by carenas** [comment]
a proposed patch for compiler-rt's builtin that has been verified to solve the problem with a manually built clang 14 based compiler in Debian 12 PowerPC64 (big endian) is available in : 

https://reviews.llvm.org/D122640

note that unlike FreeBSD, to be able to use the fix in Linux, EXTRA_LDFLAGS=--rtlib=compiler-rt is required

**Comment by carenas** [comment]
considering, I heard rumours this is fixed since FreeBSD 13.1-RC1-p1 would be a good idea to close this?

FreeBSD >= 13 might had been the only environment where this could had been triggered, since it uses clang as a base compiler in PowerPC AND supports 32-bit with that compiler (OpenBSD does use clang as well, but only 64-bit).

**Comment by pkubaj** [comment]
I merged your patch to FreeBSD, so 13.1 is now ok.

Regarding OpenBSD, 6.7 switched to clang on powerpc: https://www.openbsd.org/67.html

**Comment by PhilipHazel** [comment]
Is this issue still live, or can it be closed?

**Comment by pkubaj** [comment]
It's ok now, thanks!
